### PR TITLE
added reset trending topic button

### PR DESCRIPTION
**Pull request by chobeat**
I addressed this little ToDo. 

I have a couple questions to complete the PR: 

* what should be the styling of the button to be consistent with other admin features?
* is there a more elegant way to cast these params to integer? Or do bindings always transfer as strings? LiveView or Surface docs didn't help.

Also, I see the module has basically no testing. I can start adding some if you think it would be good.

### CODE REVIEW

**Comment by mayel** [comment]
Thanks :) 

- I couldn't find an example of a similar admin feature, but I did some quick styling and added an icon from https://iconify.design via our library https://hexdocs.pm/iconify_ex (you can see a list of icons already added to the app at http://localhost:4000/settings/instance/icons so as to try reusing the same one when possible)
- no that looks good (for more advanced use cases we use Ecto Changeset for validation/casting but not worth it here)
- some tests would indeed be great!

**Comment by mayel** [comment]
Ah I also added a called to `Boundaries.can?` to show the button only to instance modedators and admins

**Comment by chobeat** [comment]
ah yeah, the permission part was incomplete, I forgot to ask what was the right way to do it. Now I know.

**Comment by chobeat** [comment]
one question: what does ":action" do? where can I find documentation?

**Comment by mayel** [comment]
> one question: what does ":action" do? where can I find documentation?

that uses a [slot](https://surface-ui.org/slots) defined by the widget component (used to include that part in the title div)

**Pull request merged**
